### ISSUE TITLE
class jxlsave not found

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#133] opened 2021-07-01 15:47 UTC
Hello I have added NetVips 2.01 and NetVips.Native.win-x64 8.11.0

and the code

 ```
using var source = NetVips.Image.NewFromFile(@"C:\Users\fred\C.tif");
 source.Jxlsave(@"C:\Users\fred\C.tif.jxl", distance: 0.5, strip: false);
```
throw this exception
NetVips.VipsException: 'no such operation jxlsave VipsOperation: class "jxlsave" not found

what should I do to get it working?

Thank you

**Comment by kleisauke** [comment] 2021-07-02 18:07
libjxl is not yet included in pre-built libvips binaries released on NuGet. See https://github.com/kleisauke/net-vips/issues/123#issuecomment-866805565 for more information on testing this new image format on Windows.

**Comment by kleisauke** [comment] 2021-09-08 11:55
Duplicate of #123.

**Closed by kleisauke** 2021-09-08 11:55 UTC
Labels: question

**Comment by cocoon** [comment] 2021-09-23 10:58
I hope it is OK to comment here even if closed, but the error message currently can come from the fact that the applicationdirectory needs to be named "bin":
https://github.com/libvips/build-win64-mxe/issues/34
