### ISSUE TITLE
Support a single shared libvips binary on Windows

### ISSUE THREAD

**Issue by BiologyTools** [kleisauke/net-vips#211] opened 2023-07-06 19:03 UTC
I'm trying to use libvips using net-vips I have gotten libvips to work on Mac & Linux but on windows when trying to open a tiff file I get a System.AccessViolationException. I should have the proper environmental variables $VIPS_HOME, etc. set. Here is the error: System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Any suggestions on how to get libvips to work on windows?

**Comment by kleisauke** [comment] 2023-07-07 12:02
Does this happen for all TIFF images? Are you able to provide a complete, standalone code sample that allows someone else to reproduce this issue?

Note that there is no requirement to set the `VIPSHOME` or `PATH` environment variables when using the prebuilt binaries provided by the [NetVips.Native](https://www.nuget.org/packages/NetVips.Native) NuGet package.

**Comment by BiologyTools** [comment] 2023-07-08 07:22
I think the problem has something to do with the current environment set up. Since without $VIPS_HOME etc. setup I couldn't get lib_vips to start at all giving the error DllNotFoundException. I haven't tested all different types of tiff files, but with the pyramidal tiff's I have they all throw the System.AccessViolationException on windows.

**Comment by BiologyTools** [comment] 2023-07-08 09:59
Looks like this something to do with GTKSharp or something specific to my application as I can run netvips on windows before the application launches GTKSharp.

**Comment by BiologyTools** [comment] 2023-07-08 10:17
I should probably open this issue in GTKSharp? Or do you know how I can fix this environmental error? Any suggestions are welcome?

**Comment by kleisauke** [comment] 2023-07-08 12:26
It looks like this is a DLL conflict between the prebuilt GLib binaires provided by NetVips (i.e. `libglib-2.0-0.dll` and `libgobject-2.0-0.dll`) and the ones provides by GtkSharp (located in `%localappdata%\Gtk\3.24.24`).

Building a single shared libvips binary on Windows would probably fix this (see e.g. commit https://github.com/libvips/build-win64-mxe/commit/208bd40f10f004954e2fad7f152de2044c5ace10). However, this would break compatibility with other libvips bindings and the existing shared prebuilt binaries.
https://github.com/kleisauke/net-vips/blob/c83deb9186bcfaf7099c718c2d916e0775454542/src/NetVips/Interop/Libraries.Windows.cs#L5-L10

Linux and macOS doesn't have this issue after commit e04c6b0997130f06a4af2bf66c9055a529024dd1.

**Comment by BiologyTools** [comment] 2023-07-08 12:43
OK I guess I will suggest that my users download the windows only version instead of GTK to use vips on windows.

**Comment by kleisauke** [comment] 2023-09-27 09:24
I think that's a reasonable workaround.

> However, this would break compatibility with other libvips bindings and the existing shared prebuilt binaries.

With .NET version 6.0 or higher, one can implement fallback logic using [`NativeLibrary.SetDllImportResolver`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver).
https://github.com/kleisauke/net-vips/blob/3a5d4272b528a3bf46f2556e022a68358caac7a1/src/NetVips/ModuleInitializer.cs#L44-L53

But this won't work on .NET Framework. Additionally, it might be a bit too early to stop supporting .NET Standard 2.0 and Mono (see commit 3a5d4272b528a3bf46f2556e022a68358caac7a1).

I'll close this as "won't fix" for now, sorry.

**Comment by kleisauke** [comment] 2024-10-14 11:54
Re-opening now that commit 2f4f658c84132d11494ac60c73f5ad597e1844d6 and 14480400ce17a1bbb48c74e718f4d05f50e11e49 was landed. This will be available in NetVips 3.0.0 (RSN).

**Comment by kleisauke** [comment] 2024-10-14 13:08
A release candidate of NetVips 3.0.0 and NetVips.Native v8.16.0 is now available for testing.
https://www.nuget.org/packages/NetVips/3.0.0-rc1
https://www.nuget.org/packages/NetVips.Native/8.16.0-rc1

**Comment by kleisauke** [comment] 2024-10-29 12:40
[NetVips v3.0.0](https://www.nuget.org/packages/NetVips/3.0.0) and [NetVips.Native v8.16.0](https://www.nuget.org/packages/NetVips.Native/8.16.0) is now available.

**Closed by kleisauke** 2024-10-29 12:40 UTC
Labels: enhancement
