### ISSUE TITLE
heifsave

### ISSUE THREAD

**Issue by randyridge** [kleisauke/net-vips#104] opened 2020-12-23 17:33 UTC
heifsave is currently failing for me, I imagine this will be added when 8.10.5 gets finalized?

**Comment by randyridge** [comment] 2020-12-24 15:45
As a followup still no joy on win64 with the final 8.10.5 with 1.2.4 and latest from master.  I also tried vips-dev-x64-all-8.10.5, Heifsave(path, 50, false, "av1", true) exits process with -1073741795.

**Comment by kleisauke** [comment] 2020-12-24 16:13
Yes, I'm currently preparing NetVips.Native v8.10.5 and NetVips v1.2.5 (for exposing the "speed" parameter in heifsave).

Exit code `-1073741795` (`0xC000001D` - ` STATUS_ILLEGAL_INSTRUCTION`) looks like a serious issue. Are you able to provide a standalone code sample that demonstrates this problem? This seems to work for me without any problems:
```csharp
var im = Image.NewFromFile("images/lichtenstein.jpg", access: Enums.Access.Sequential);
im.Heifsave("lichtenstein.avif", q: 50, compression: Enums.ForeignHeifCompression.Av1, speed: 6, strip: true);
```
(the CI also passes for Windows, although the Linux ARM64v8 build fails which should be fixed with  https://github.com/kleisauke/libvips-packaging/commit/b894afcc3d6e232e1a02ea721cc46c8e3e8590b5)

**Comment by kleisauke** [comment] 2020-12-24 16:15
Oh wait, was `vips-dev-w64-all-8.10.5.zip` downloaded from https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.5 or https://github.com/libvips/libvips/releases/tag/v8.10.5?

**Comment by randyridge** [comment] 2020-12-24 16:53
I pulled down latest netvips from master, referenced it in a .net 5 console app, copied the contents of the x64 all package to runtimes/winx64/native, then public static void Main() =>Image.NewFromFile(TestFiles.InputJpg).Heifsave("lichtenstein.avif", q: 50, compression: Enums.ForeignHeifCompression.Av1, speed: 6, strip: true);  the file in this case is 2569067123_aca715a2ee_o.jpg from sharp's test images.

The first link I get the exit code -1073741795, the second link results in NetVips.VipsException: 'no such operation heifsave VipsOperation: class "heifsave" not found'.

**Comment by kleisauke** [comment] 2020-12-24 19:30
I still had no luck reproducing it. When running your reproduction repo it writes a 117 kB AVIF image in `ConsoleApp1/bin/Release/net5.0`. I also tried to run it with the `x64` platform instead of `Any CPU`, but that works also fine.

Could you try to run it with vips cli (to exclude .NET and NetVips)?
```cmd
vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true]
```

(the `no such operation heifsave ...` error is expected for the second link, as those binaries are built without AVIF support)

**Comment by randyridge** [comment] 2020-12-24 19:51
produces a 0 byte file

**Comment by kleisauke** [comment] 2020-12-24 20:26
Which CPU do you have? Does it support the [SSE, SSE2, SSE3, SSE4.1, AVX, AVX2](https://aomedia.googlesource.com/aom/+/df1c606cc24d718bab266f7439c9fc550a35fd56/build/cmake/cpu.cmake#70) instruction sets?

**Comment by randyridge** [comment] 2020-12-24 21:02
It's an old core i7, has mmx, sse, sse2, sse3, ssse3, sse4.1, sse 4.2, em64t, aes, avx.

**Comment by kleisauke** [comment] 2020-12-25 10:24
Could you try running it with the [`AOM_SIMD_CAPS`](https://aomedia.googlesource.com/aom/+/df1c606cc24d718bab266f7439c9fc550a35fd56/aom_ports/x86.h#178) environment variable set to `383` (or to `0` to disable SIMD completely). Otherwise, I've to look for a PC with a CPU that doesn't support AVX2 (my Windows laptop and PC both support this instruction set).

fwiw, here's a small C-program to generate this value:
<details>
  <summary>Details</summary>

```c
#include <stdio.h>

#define HAS_MMX 0x01
#define HAS_SSE 0x02
#define HAS_SSE2 0x04
#define HAS_SSE3 0x08
#define HAS_SSSE3 0x10
#define HAS_SSE4_1 0x20
#define HAS_AVX 0x40
#define HAS_AVX2 0x80
#define HAS_SSE4_2 0x100

int main()
{
  unsigned int flags = 0;
  flags |= HAS_MMX;
  flags |= HAS_SSE; /* aka xmm */
  flags |= HAS_SSE2; /* aka wmt */
  flags |= HAS_SSE3;
  flags |= HAS_SSSE3;
  flags |= HAS_SSE4_1;
  flags |= HAS_SSE4_2;
  flags |= HAS_AVX;
  //flags |= HAS_AVX2;

  printf("%u\n", flags);

  return 0;
}
```
</details>

**Comment by randyridge** [comment] 2020-12-26 13:32
Seemingly didn't have the expected result:

\vips-dev-8.10\bin
❯ $AOM_SIMD_CAPS=0
❯ $AOM_SIMD_CAPS
0
❯ .\vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true]
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/26/2020  8:30 AM              0 x.avif

**Comment by kleisauke** [comment] 2020-12-26 14:21
Ah, testing this option doesn't seem to make any difference indeed. The Windows binaries seems to build aom with `-DCONFIG_RUNTIME_CPU_DETECT=0`, which is probably wrong:
https://github.com/libvips/build-win64-mxe/blob/bf2884b50789920e14382f7f8975020ba2f0a2cf/build/aom.mk#L16

This build option was introduced to fix the ARMv7 and ARM64 build failures, and I thought it wasn't relevant for Windows 32- and 64 bits, but it seems to be used there:
https://aomedia.googlesource.com/aom/+/df1c606cc24d718bab266f7439c9fc550a35fd56/build/cmake/rtcd.pl#145

I'm building a test binary now with this option removed.

/cc @lovell as this also affects sharp.

**Comment by kleisauke** [comment] 2020-12-26 14:35
Here is a test binary that was built without this option:
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-web-8.10.5-static.zip

Are you able to test that? It seems to recognize the `AOM_SIMD_CAPS` environment variable for me now:
```powershell
C:\vips-dev-8.10\bin> $results = Measure-Command { .\vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true] }
C:\vips-dev-8.10\bin> $results | Format-List *
Ticks             : 54865141
Days              : 0
Hours             : 0
Milliseconds      : 486
Minutes           : 0
Seconds           : 5
TotalDays         : 6,35013206018518E-05
TotalHours        : 0,00152403169444444
TotalMilliseconds : 5486,5141
TotalMinutes      : 0,0914419016666667
TotalSeconds      : 5,4865141
C:\vips-dev-8.10\bin> $env:AOM_SIMD_CAPS = "0"
C:\vips-dev-8.10\bin> $results = Measure-Command { .\vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true] }
C:\vips-dev-8.10\bin> $results | Format-List *
Ticks             : 133548046
Days              : 0
Hours             : 0
Milliseconds      : 354
Minutes           : 0
Seconds           : 13
TotalDays         : 0,000154569497685185
TotalHours        : 0,00370966794444444
TotalMilliseconds : 13354,8046
TotalMinutes      : 0,222580076666667
TotalSeconds      : 13,3548046
```

**Comment by randyridge** [comment] 2020-12-26 15:08
That works with and and seemingly without AOM_SIMD_CAPS set to 0.

```
❯ $AOM_SIMD_CAPS
❯ $results = Measure-Command { .\vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true] }
❯ $results | Format-List *

Ticks             : 169855490
Days              : 0
Hours             : 0
Milliseconds      : 985
Minutes           : 0
Seconds           : 16
TotalDays         : 0.000196592002314815
TotalHours        : 0.00471820805555556
TotalMilliseconds : 16985.549
TotalMinutes      : 0.283092483333333
TotalSeconds      : 16.985549


❯ $env:AOM_SIMD_CAPS = "0"
❯ $results = Measure-Command { .\vips copy 2569067123_aca715a2ee_o.jpg x.avif[Q=50,compression=av1,speed=6,strip=true] }
❯ $results | Format-List *

Ticks             : 338543408
Days              : 0
Hours             : 0
Milliseconds      : 854
Minutes           : 0
Seconds           : 33
TotalDays         : 0.000391832648148148
TotalHours        : 0.00940398355555556
TotalMilliseconds : 33854.3408
TotalMinutes      : 0.564239013333333
TotalSeconds      : 33.8543408
```

**Comment by kleisauke** [comment] 2020-12-26 19:56
Great! I'll shortly fix this in `8.10.5-build2` on the [build-win64-mxe](https://github.com/libvips/build-win64-mxe) repo and release it as `8.10.5.1` on NuGet (since NuGet treats `-build*` suffixes as prereleases). 

Just wondering, were you able to decode AVIF images with the v8.10.5 binaries? I'm not sure if this bug only affects AVIF encoding.

**Comment by kleisauke** [comment] 2020-12-26 20:00
Also, thanks for reporting and testing this so quickly!

**Comment by randyridge** [comment] 2020-12-26 20:13
I've not attempted decoding avif yet, I'll do so later today.

Thanks for the quick turnaround!

**Comment by kleisauke** [comment] 2020-12-27 14:56
Fixed with https://github.com/libvips/build-win64-mxe/commit/131a9d01a634406d9bed78b9e71407581c3aba86 and released as [NetVips.Native v8.10.5.1](https://www.nuget.org/packages/NetVips.Native/8.10.5.1) on NuGet. Thanks again!

**Closed** 2020-12-27 15:05 UTC
Labels: bug

**Comment by lovell** [comment] 2020-12-27 21:17
@kleisauke I'll repackage the prebuilt binaries provided for sharp too, thanks for alerting me to this.
