### ISSUE TITLE
Files are still locked after dispose/close

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#12] opened 2018-07-23 15:01 UTC
Hi,
I need to cleanup a file after having been "tumbnailed" with NetVips. But it seems that files are still locked depsite even outside the "using" blocks. Do I miss something ?

```
            using (var image = NetVips.Image.NewFromFile(fileClone))
            using (var thumb = image.ThumbnailImage(250)) {
                Console.WriteLine(thumb.Width);
                thumb.WriteToFile(string.Concat(fileClone, ".thumbnail.jpeg"));
            }

            File.Delete(fileClone);
```

If I comment the "thumb.WriteToFile" line, the file is no longer locked though and can be deleted. Seems to be related to WriteToFile.

I did try to explicitly call the "Close" method on both Image objects (in case it's not done ine the Dipose). Still no luck...

Thanks for your attention !

**Comment by kleisauke** [comment] 2018-07-23 16:06
Hello, please see https://github.com/kleisauke/net-vips/issues/6#issuecomment-394379299 and [the corresponding libvips documentation](https://jcupitt.github.io/libvips/API/current/VipsOperation.html#vips-cache-set-max-files).

**Comment by gjactat** [comment] 2018-07-23 22:14
Files are still locked, even with "VipsCacheSetMax" set to 0.
I'll try to change the whole workflow to avoid deletions.
Thanks anyway for your quick feedback !

**Comment by gjactat** [comment] 2018-07-23 22:50
It seems that explicit GarbageCollector call *with* VipsCache set to 0 indeed release file handles.
These two factors would probably have a noticeable impact on performances.

**Comment by kleisauke** [comment] 2018-07-24 14:21
I've reproduced this on Windows (on Linux it's fine). It seems that the file is being held open in libvips.

As you describe, an immediate garbage collection resolves this. Indeed, this would have a noticeable impact on performance and feels a bit unnatural to do (the best practice is to not force a garbage collection in most cases).

@jcupitt Any idea what the root cause might be? I can remember that we have experienced this before on Windows, see: https://github.com/jcupitt/ruby-vips/issues/118#issuecomment-324005155.

Also just reproduced this on pyvips (on my Windows PC):
```python
import logging
import os
import gc

import pyvips

logging.basicConfig(level=logging.DEBUG)
pyvips.cache_set_max(0)

file_name = 'lichtenstein'
extension = 'jpg'

thumb = pyvips.Image.thumbnail('{}.{}'.format(file_name, extension), 250)
thumb.write_to_file('{}.thumbnail.{}'.format(file_name, extension))

# no effect
gc.collect()

# being used by another process
os.remove('{}.{}'.format(file_name, extension))
```

**Comment by jcupitt** [comment] 2018-07-24 14:55
Huh strange. 

I can't get to my Windows PC until the end of the week, unfortunately. My sister-in-law is staying and she's sleeping in the study.

You could try inserting calls to `vips_tracked_get_files()`. It returns the number files that libvips knows are open. Hopefully you'll see the number go up and down correctly as files are processed.  

http://jcupitt.github.io/libvips/API/current/libvips-memory.html#vips-tracked-get-files

**Comment by kleisauke** [comment] 2018-08-07 13:39
I had some time to look at this, but couldn't find the cause yet. I've added `vips_tracked_get_files()` just after the `WriteToFile` operation (after it is being thumbnailed), see:
https://github.com/kleisauke/net-vips/blob/498438851aaaabda70b73faade1c6622174644dc/tests/NetVips.Tests/LeakTests.cs#L53

This yields `0` as expected. The unit tests passes cleanly on Windows and Linux.

**Comment by kleisauke** [comment] 2018-08-13 11:59
Update:
It seems that only `.jpg`, `.tiff` and `.pdf` files are affected (`.fits` and `.exr` may also be affected). See this testcase:

```csharp
var loaderFileDict = new Dictionary<string, string>
{
    {"jpegload", Helper.JpegFile},
    {"tiffload", Helper.TifFile},
    {"pdfload", Helper.PdfFile},
    {"matload", Helper.MatlabFile},
    {"pngload", Helper.PngFile},
    {"analyzeload", Helper.AnalyzeFile},
    {"gifload", Helper.GifFile},
    {"webpload", Helper.WebpFile},
    {"fitsload", Helper.FitsFile},
    {"openslideload", Helper.OpenslideFile},
    {"openexrload", Helper.ExrFile},
    {"svgload", Helper.SvgFile},
    {"magickload", Helper.BmpFile},
};

foreach (var entry in loaderFileDict)
{
    if (!Helper.Have(entry.Key))
    {
        Console.WriteLine($"No {entry.Key}, skipping delete test");
        continue;
    }

    // Make sure it's disposed correctly.
    using (var image = Image.NewFromFile(entry.Value))
    {
        image.WriteToFile(Path.GetRandomFileName() + ".jpg");
    }

    try
    {
        File.Delete(entry.Value);
        Console.WriteLine($"Successfully deleted file from {entry.Key}");
    }
    catch (Exception)
    {
        Console.WriteLine($"{entry.Key} needs to be fixed");
    }
}
```

```
jpegload needs to be fixed
tiffload needs to be fixed
pdfload needs to be fixed
Successfully deleted file from matload
Successfully deleted file from pngload
Successfully deleted file from analyzeload
Successfully deleted file from gifload
Successfully deleted file from webpload
No fitsload, skipping delete test
Successfully deleted file from openslideload
No openexrload, skipping delete test
Successfully deleted file from svgload
Successfully deleted file from magickload
```

(tested with `vips-dev-w64-all-8.7.0.zip`)

**Comment by kleisauke** [comment] 2018-08-14 11:40
Cache was set to 0 in that example. I also made one in Python, see:
```python
#!/usr/bin/python

import os

import pyvips

pyvips.cache_set_max(0)

images_dir = "C:\\test-suite\\images"

loader_file_dict = {
    "jpegload": os.path.join(images_dir, "йцук.jpg"),
    "tiffload": os.path.join(images_dir, "sample.tif"),
    "pdfload": os.path.join(images_dir, "ISO_12233-reschart.pdf"),
    "matload": os.path.join(images_dir, "sample.mat"),
    "pngload": os.path.join(images_dir, "sample.png"),
    "analyzeload": os.path.join(images_dir, "t00740_tr1_segm.hdr"),
    "gifload": os.path.join(images_dir, "cramps.gif"),
    "webpload": os.path.join(images_dir, "1.webp"),
    "fitsload": os.path.join(images_dir, "WFPC2u5780205r_c0fx.fits"),
    "openslideload": os.path.join(images_dir, "CMU-1-Small-Region.svs"),
    "openexrload": os.path.join(images_dir, "sample.exr"),
    "svgload": os.path.join(images_dir, "vips-profile.svg"),
    "magickload": os.path.join(images_dir, "MARBLES.BMP"),
}

for loader, file in loader_file_dict.items():
    if pyvips.type_find("VipsOperation", loader) == 0:
        print("No {}, skipping test".format(loader))
        continue

    image = pyvips.Image.new_from_file(file)
    image_loader = image.get('vips-loader')

    if image_loader != loader:
        print("Loaded from {} instead than {}, skipping test".format(image_loader, loader))
        continue

    # image.write_to_file("x.v")
    buf = image.write_to_buffer(".jpg")

    try:
        os.remove(file)
        print("Successfully deleted file from {}".format(loader))
    except IOError:
        print("Could not delete file from {}".format(loader))
```

(where `C:\\test-suite\\images` is the location of [libvips test suite images](https://github.com/jcupitt/libvips/tree/master/test/test-suite/images))

On Linux I see:

```
Successfully deleted file from jpegload
Successfully deleted file from tiffload
Successfully deleted file from pdfload
Successfully deleted file from matload
Successfully deleted file from pngload
Successfully deleted file from analyzeload
Successfully deleted file from gifload
Successfully deleted file from webpload
Successfully deleted file from fitsload
Successfully deleted file from openslideload
Successfully deleted file from openexrload
Successfully deleted file from svgload
Successfully deleted file from magickload
```

However on Windows:
```
Could not delete file from jpegload
Could not delete file from tiffload
Could not delete file from pdfload
Successfully deleted file from matload
Successfully deleted file from pngload
Successfully deleted file from analyzeload
Successfully deleted file from gifload
Successfully deleted file from webpload
No fitsload, skipping test
Successfully deleted file from openslideload
No openexrload, skipping test
Successfully deleted file from svgload
Successfully deleted file from magickload
```

**Comment by kleisauke** [comment] 2018-08-14 11:50
Same behavior on libvips 8.5.9 (I thought it was because of https://github.com/jcupitt/libvips/issues/729).

Maybe `close` is called too late? See: https://github.com/jcupitt/libvips/blob/01b66f5ccd6e1c6f6fbcaae2ccf9353de6b60f39/libvips/foreign/jpeg2vips.c#L263-L264

I'll try to build libvips with GLib 2.57.2 and see if that solves it.

**Comment by jcupitt** [comment] 2018-08-14 16:55
Your linux test should look at `/proc/$pid/fd`, I think. Delete will always succeed on linux, even if the file is open.

There's a Windows thing to explore the open handles on a process, perhaps that could give some clues?

**Comment by jcupitt** [comment] 2018-08-14 17:28
Huh that's an interesting find.

Windows has a lot of different file APIs: `_open()`, `_wopen()`, `CreateFile()` etc. etc. Perhaps tiff / jpg / pdf are using different ones from mat / png / gif?

I know that libtiff at least can be configured with different file backends on Windows.

**Comment by kleisauke** [comment] 2018-08-15 13:41
With the above commit and [these pre-compiled libvips binaries](https://github.com/kleisauke/build-win64-mxe/releases/tag/v8.7.0-rc1), it seems this issue is gone. See:

```
Successfully deleted file from jpegload
Successfully deleted file from tiffload
Successfully deleted file from pdfload
Successfully deleted file from matload
Successfully deleted file from pngload
Successfully deleted file from analyzeload
Successfully deleted file from gifload
Successfully deleted file from webpload
No fitsload, skipping test
Successfully deleted file from openslideload
No openexrload, skipping test
Successfully deleted file from svgload
Successfully deleted file from magickload
```

You can see this as a hotfix, I'm not sure why libvips keeps the file handles open on Windows. I tried to explore the open file handles of a process for Windows, and it seems that they are still open after adding `time.sleep(200)` after the `write_to_buffer` call (to check if this isn't a timing issue).

Note that the file handles are closed for NetVips after an immediate garbage collection and for pyvips after the Python script terminates (`gc.collect()` has no effect). I will try some other libvips bindings to check what behavior they exhibit.

**Comment by jcupitt** [comment] 2018-08-15 14:02
I switched libvips to always use g_open()/g_fopen() -- I'm not sure I understand how it helps here, but it's certainly neater.

Patching in `FILE_SHARE_DELETE` feels a bit ugly :( Why do libtiff and libpoppler leave these handles open?

**Comment by jcupitt** [comment] 2018-08-15 14:03
... but great detective work of course tracking this down!

**Comment by gjactat** [comment] 2018-08-15 14:32
Thanks for this amazing chase !

**Comment by kleisauke** [comment] 2018-08-15 18:50
I have found a proper fix for jpegload. See:
```diff
diff --git a/libvips/foreign/jpeg2vips.c b/libvips/foreign/jpeg2vips.c
index 1111111..2222222 100644
--- a/libvips/foreign/jpeg2vips.c
+++ b/libvips/foreign/jpeg2vips.c
@@ -668,7 +668,7 @@ read_jpeg_generate( VipsRegion *or,
 	 * object, destroy as soon as we can. Safe to call many times. 
 	 */
 	if( jpeg->y_pos >= or->im->Ysize ) 
-		jpeg_destroy_decompress( &jpeg->cinfo );
+		(void) readjpeg_free( jpeg );
 
 	VIPS_GATE_STOP( "read_jpeg_generate: work" );
 
```

This will also close the file handles as soon as possible. `tiffload` and `pdfload` are the next loaders that I'm going to examine.

(with the above commit I also removed those ugly `FILE_SHARE_DELETE` patches)

**Comment by kleisauke** [comment] 2018-08-16 09:48
I have also managed to fix `tiffload` and `pdfload`, see:
```diff
diff --git a/libvips/foreign/tiff2vips.c b/libvips/foreign/tiff2vips.c
index 1111111..2222222 100644
--- a/libvips/foreign/tiff2vips.c
+++ b/libvips/foreign/tiff2vips.c
@@ -1880,6 +1880,9 @@ rtiff_stripwise_generate( VipsRegion *or,
 		y += hit.height;
 	}
 
+	if( y >= or->im->Ysize - r->top ) 
+		VIPS_FREEF( TIFFClose, rtiff->tiff );
+
 	VIPS_GATE_STOP( "rtiff_stripwise_generate: work" ); 
 
 	return( 0 );

diff --git a/libvips/foreign/pdfload.c b/libvips/foreign/pdfload.c
index 1111111..2222222 100644
--- a/libvips/foreign/pdfload.c
+++ b/libvips/foreign/pdfload.c
@@ -393,6 +393,10 @@ vips_foreign_load_pdf_generate( VipsRegion *or,
 			(guint32 *) VIPS_REGION_ADDR( or, r->left, r->top + y ), 
 			r->width ); 
 
+	if( y >= or->im->Ysize ) 
+		VIPS_UNREF( pdf->page );
+		VIPS_UNREF( pdf->doc );
+
 	return( 0 ); 
 }
 
```

The pyvips and NetVips test is now running smoothly. I'm going to try to build the vips-all binary with OpenEXR, FITS and NIfTI support because these loaders have not yet been tested.

Thanks for reporting this! I think this improvement will be in libvips 8.7.

**Comment by jcupitt** [comment] 2018-08-16 14:16
I thought about this a little more to try to get it clear in my head.

The current behaviour (close input handles on unref) works for languages like C / C++ / Python / Rust / etc., where things get unreffed automatically when they go out of scope. 

On languages like Ruby / C# / node / etc., where things are unreffed on GC, files can stay open for a long time after you've finished with them. This interacts in an unfortunate way with the Windows default of refusing to remove open files. 

Kleis' change closes file handles as soon as the scan of the input file finishes, and therefore produces something closer to expected behaviour for GCd languages on Windows. 

I'll see if I can make a PR which implements this change in a consistent way.

**Comment by kleisauke** [comment] 2018-08-16 14:50
A more consistent way would be useful. I found this while I was browsing through the `vipspng.c` source (see [here](https://github.com/jcupitt/libvips/blob/f3ef6e52eaa4c4f83f0681219cbbf134899789dc/libvips/foreign/vipspng.c#L592) for that `Ysize` logic, note that it's calling `read_destroy` which closes the used file descriptors). I thought that the the other loaders might also benefit from this logic (I don't think there is a reason to keep the file descriptors open after `vips_image_generate` has finished).

For implementing this in a more consistent way;
We could maybe add a `VipsDisposeFn` to [`vips_image_generate`](https://github.com/jcupitt/libvips/blob/f3ef6e52eaa4c4f83f0681219cbbf134899789dc/libvips/iofuncs/generate.c#L680) which will be called when it has finished reading, the class may then close the file descriptors.

**Comment by jcupitt** [comment] 2018-08-16 19:09
I had a go. I changed TIFF and JPEG load.

I think PDF will be hard to fix -- `pdfload` supports random access to pixels, so reaching the bottom of the image isn't a guarantee that no more pixels are needed. I think we'd need to revise the load system so that seq mode became a thing that loaders explicitly supported or didn't support, with its own code path.

I think a big change like that is too late for 8.7, it'll need to be something we think about for 8.8.

**Comment by jcupitt** [comment] 2018-08-17 10:30
Of course I slept on it and pdf is easy, duh. I've made a PR -- if someone could test it, we can merge for 8.7.

**Comment by kleisauke** [comment] 2018-08-18 20:09
Output of the Python script with all loaders (including `fitsload`, `openexrload`, `niftiload`) on Windows:
```
Successfully deleted file from jpegload
Could not delete file from tiffload
Successfully deleted file from pdfload
Successfully deleted file from matload
Successfully deleted file from pngload
Successfully deleted file from analyzeload
Successfully deleted file from gifload
Successfully deleted file from webpload
Could not delete file from fitsload
Successfully deleted file from openslideload
Could not delete file from openexrload
Successfully deleted file from svgload
Successfully deleted file from magickload
Successfully deleted file from niftiload
```

`tiffload` is fixable with `if( y - r->top >= or->im->Ysize )` (not sure if that is correct). I'll see tomorrow whether it's possible to patch `fitsload` and `openexrload`.

**Comment by kleisauke** [comment] 2018-08-19 21:12
[PR #1066](https://github.com/jcupitt/libvips/pull/1066) has been merged to master, this improvement will be in libvips 8.7. Thanks again for reporting this!

**Comment by kleisauke** [comment] 2018-09-25 19:46
I've just released NetVips 1.0.5 which bundle and depend upon libvips 8.7.

**Closed by kleisauke** 2018-09-25 19:46 UTC
Labels: blocked-upstream-dependency, bug

**Comment by kalozka1** [comment] 2019-07-08 13:37
Hi guys,

I found a case when the files remain locked...
Im using on windows the NetVips version 1.0.7 with the standard libvips version it comes with (i think it is 8.7).

When i try to create a thumbnail:
`img.Jpegsave(outputFileFullPath, strip: true, background: new double[] { 255, 255, 255 });`
in some cases i cannot delete the file.

As far i can see it has to do with the rows per strip property in a tif file.
When this value is extreme like 1 or 3100 the file stays open, but when i use an image which has a rows per strip value for ex. 28 than the process works fine, and the file doesn't stay open...

Here you have an example file (yes, it's white):
https://we.tl/t-HJFBcjorIc

If you open the file in photoshop and saving it without any changes, or ask imagemagick to set the strips per row to 28 then the file doesn't stay open/locked..

Thx!

**Comment by kalozka1** [comment] 2019-07-08 14:02
Here you have an other example, where even the color space and profile is the same for both images:
[](https://we.tl/t-WsbLyth2vu)
Do you have any idea how can i deal with this?
It is eating up a lot of space when i cant touch the files after processing them.

**Comment by kleisauke** [comment] 2019-07-08 14:42
@kalozka1 I tried this test script with the images you provided:

```csharp
var files = new List<string>
{
    "5000x10000.tif",
    "5000x10000-rowsperstrip1.tif",
    "1rowsperstrip.tif",
    "17rowsperstrip.tif"
};

foreach (var file in files)
{
    // Make sure it's disposed correctly.
    using (var image = Image.NewFromFile(file))
    {
        image.WriteToFile(Path.GetRandomFileName() + ".jpg");
    }

    try
    {
        File.Delete(file);
        Console.WriteLine($"Successfully deleted {file}");
    }
    catch (Exception)
    {
        Console.WriteLine($"{file} couldn't be deleted");
    }
}
```

With NetVips v1.0.7 (bundled with libvips 8.7.4), I see this (on my Windows PC):

```
Successfully deleted 5000x10000.tif
Successfully deleted 5000x10000-rowsperstrip1.tif
Successfully deleted 1rowsperstrip.tif
Successfully deleted 17rowsperstrip.tif
```

Same results with NetVips v1.1.0-rc3 and libvips 8.8.0.

**Comment by kalozka1** [comment] 2019-07-09 06:00
Thank you for the quick reaction!

Your code indeed works for me as well.
Here you see my code:

```
var files = new List<string>
            {
                "5000x10000.tif",
                "5000x10000-rowsperstrip1.tif",
                "1rowsperstrip.tif",
                "17rowsperstrip.tif"
            };

            foreach (var file in files)
            {
                // Make sure it's disposed correctly.
                using (var outputImage = NetVips.Image.Thumbnail(file, 510, 510))
                {
                    outputImage.Jpegsave(Path.GetRandomFileName() + ".jpg");
                }

                try
                {
                    File.Delete(file);
                    Console.WriteLine($"Successfully deleted {file}");
                }
                catch (Exception)
                {
                    Console.WriteLine($"{file} couldn't be deleted");
                }
            }
```

The result is:

```
Successfully deleted 5000x10000.tif
5000x10000-rowsperstrip1.tif couldn't be deleted
1rowsperstrip.tif couldn't be deleted
Successfully deleted 17rowsperstrip.tif
```

**Comment by kleisauke** [comment] 2019-07-09 11:01
Thanks, I could reproduce this with libvips 8.7.4, 8.8.0 and 8.8.1.

@jcupitt It seems it's not closing input early for this case (it only happens during thumbnailing, strange). I've enabled debug within `tiff2vips` and saw that it's reading strips until `9998`:
```
$ vipsthumbnail 5000x10000-rowsperstrip1.tif -s 150x150
tiff2vips: libtiff starting for 5000x10000-rowsperstrip1.tif
tiff2vips: reading header for page 0 ...
rtiff_set_page: selecting page 0
rtiff_n_pages: found 1 pages
tiff2vips: rtiff_read_stripwise
rtiff_set_header: header.samples_per_pixel = 1
rtiff_set_header: header.bits_per_sample = 8
rtiff_set_header: header.sample_format = 1
rtiff_set_header: header.orientation = 1
rtiff_read_stripwise: header.rows_per_strip = 1
rtiff_read_stripwise: header.strip_size = 5000
rtiff_read_stripwise: header.number_of_strips = 10000
rtiff_read_stripwise: header.read_height = 1
rtiff_read_stripwise: header.read_size = 5000
...

rtiff_stripwise_generate: top = 9998, height = 1
rtiff_stripwise_generate: y_top = 9998
rtiff_strip_read: reading strip 9998
```

which causes that the following code isn't executed:
https://github.com/libvips/libvips/blob/063234fde1a96ddadcf5bee8e4a3ccaf6cc6baf4/libvips/foreign/tiff2vips.c#L1954-L1959

This seems to work fine:
```
$ vips copy 5000x10000-rowsperstrip1.tif x.jpg
...

rtiff_stripwise_generate: top = 9998, height = 1
rtiff_stripwise_generate: y_top = 9998
rtiff_strip_read: reading strip 9998
rtiff_stripwise_generate: top = 9999, height = 1
rtiff_stripwise_generate: y_top = 9999
rtiff_strip_read: reading strip 9999
rtiff_stripwise_generate: early shutdown
```

**Comment by kalozka1** [comment] 2019-07-09 11:33
I think this means that i need to give up on using the thumbnailing till we get a version update.

Can you confirm that I'm loosing some performance benefit of thumbnailing when i use the other approach instead:

```
   using (var image = Image.NewFromFile(file))
    {
        image.WriteToFile(Path.GetRandomFileName() + ".jpg");
    }
```

**Comment by kleisauke** [comment] 2019-07-09 11:39
@kalozka1 You can use the buffer methods as a work-around:
```csharp
using (var image = Image.ThumbnailBuffer(File.ReadAllBytes(file), 510, height: 510))
{
    image.Jpegsave(Path.GetRandomFileName() + ".jpg");
    // Or:
    // image.WriteToFile(Path.GetRandomFileName() + ".jpg");
}
```

**Comment by jcupitt** [comment] 2019-07-09 11:41
Here's a possible clue:

```
john@kiwi:~/pics$ vips shrinkv 5000x10000-rowsperstrip1.tif x.v 100
rtiff_stripwise_generate: early shutdown
john@kiwi:~/pics$ vips shrinkv 5000x10000-rowsperstrip1.tif x.v 113
john@kiwi:~/pics$ 
```

So if you shrink by something that is not a factor of the vertical height, `shrinkv` will sometimes not ask for the final line in the file and will not trigger early shutdown.

**Comment by jcupitt** [comment] 2019-07-09 11:55
Oh, it's if `shrinkv` rounds down.

For example, if the input is 10,000 pixels high and it's shrinking by 113, the output image is 10,000 / 113, or 88.496 pixels. This is rounded to nearest, so 88 pixels high.

The 88th line of the output is made from the the 113 lines starting at 87 * 113 or 9831, with the bottom line at 9944. So it never fetches the last line of the tif.

**Comment by kalozka1** [comment] 2019-07-09 12:12
Thanks @kleisauke for the quick response!
I will apply the buffered approach.

**Comment by jcupitt** [comment] 2019-07-09 16:00
I tried a quick hack and it seems to fix the shrinkv case at least. What do you think?

**Comment by kleisauke** [comment] 2019-07-10 15:30
Thanks John! This seems to work fine. 👍 

I'm not sure if this logic should also be added to `reducev`. I've thumbnailed the `5000x10000-rowsperstrip1.tif` image within the 1-5000 range (both width and height) and did not experience any problems.

By the way, that `VIPS_ROUND_UP` logic seems rather interesting. Could perhaps `reducev` also benefit from this?

**Comment by jcupitt** [comment] 2019-07-10 16:46
OK, merged to 8.8, this will be in 8.8.2. Thanks for pointing this dumbness out.

I had a quick look at reducev Kleis and coun't see a useful place to add it. shrinkh could use it, but it wouldn't make any difference (I think).

**Comment by kalozka1** [comment] 2019-07-18 05:05
Hi guys!

I found an other case when the file is kept locked (the code and the lib versions are unchanged)...
I think the image i try to generate thumb for is corrupted, but still i would like to delete from the temp location when the thumb generation failed.

`
NetVips.VipsException: unable to call dzsave
TIFFFillStrip: Read error at scanline 256; got 26132 bytes, expected 68734
tiff2vips: read error

   at NetVips.Operation.Call(String operationName, VOption kwargs, Object[] args)
   at NetVips.Image.Dzsave(String filename, String basename, String layout, Nullable`1 pageHeight, String suffix, Nullable`1 overlap, Nullable`1 tileSize, Nullable`1 centre, String depth, String angle, String container, Nullable`1 properties, Nullable`1 compression, String regionShrink, Nullable`1 strip, Double[] background)
   at Phomas.Generator.Handler.Handler.DeepZoomGeneratorVIPS.GenerateZoom(String sourceFileFullPath, String targetFolderFullPath, Int32 maxLevel)
   at Phomas.Generator.Handler.Handler.DeepZoomGeneratorVIPS.Handle(IDerivativeRequestModel iModel, String sourceFileFullPath, ShotMetadataModel shotMetadata)
   at Phomas.Generator.BLService.GeneratorService.HandleItemsToGenerate(String cachedSourceFileFullPath, IEnumerable`1 itemsToGenerate, ShotMetadataModel shotMetadata)
`

Do you have an idea how can i get around this?

**Comment by kalozka1** [comment] 2019-07-18 07:02
I'm using the NetVips version 1.0.7 with the standard libvips version it comes with on windows.

**Comment by jcupitt** [comment] 2019-07-18 08:11
Would forcing a GC free the handle?

**Comment by kleisauke** [comment] 2019-07-18 08:37
@kalozka1 Are you able to share your `corrupted.tif`? I tried this:
```
head -c 1260000 5000x10000-rowsperstrip1.tif > corrupted.tif
```
But that seems to work fine.

**Comment by kalozka1** [comment] 2019-07-18 10:46
Here you go:
https://we.tl/t-AXmV1aMeww

**Comment by kleisauke** [comment] 2019-07-18 12:50
Thanks, I can reproduce this with:
```csharp
const string file = "corrupted.tif";

try
{
    using (var image = Image.NewFromFile(file/*, access: "sequential"*/))
    {
        // image.Dzsave(file + "_output");
        image.WriteToFile("x.tif");
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
finally
{
    try
    {
        File.Delete(file);
        Console.WriteLine($"Successfully deleted {file}");
    }
    catch (Exception)
    {
        Console.WriteLine($"{file} couldn't be deleted");
    }
}
```


@jcupitt This patch seems to work for me (only for random access, it doesn't work for sequential access(?)):
```diff
diff --git a/libvips/foreign/tiff2vips.c b/libvips/foreign/tiff2vips.c
index 1111111..2222222 100644
--- a/libvips/foreign/tiff2vips.c
+++ b/libvips/foreign/tiff2vips.c
@@ -2372,12 +2372,16 @@ vips__tiff_read( const char *filename, VipsImage *out,
 		return( -1 );
 
 	if( rtiff->header.tiled ) {
-		if( rtiff_read_tilewise( rtiff, out ) )
+		if( rtiff_read_tilewise( rtiff, out ) ) {
+			rtiff_free( rtiff );
 			return( -1 );
+		}
 	}
 	else {
-		if( rtiff_read_stripwise( rtiff, out ) )
+		if( rtiff_read_stripwise( rtiff, out ) ) {
+			rtiff_free( rtiff );
 			return( -1 );
+		}
 	}
 
 	return( 0 );

```

This will early shut down the input file for corrupt images / read errors. Perhaps other loaders may also need a similar patch.

**Comment by kleisauke** [comment] 2019-07-18 13:26
Let us continue this discussion in https://github.com/libvips/libvips/issues/1370.

**Comment by kleisauke** [comment] 2019-07-29 21:03
NetVips v1.1.0 / NetVips.Native v8.8.1 is now available. The commits from the above issue has been integrated within the pre-compiled libvips binaries for Windows.

If you're still experiencing problems, please feel free to open a new issue.
